// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA7gI3qG4YuOzg4YlP8HuurMIl-qyvODs',
    appId: '1:525959382347:web:8f05936626459c031794ce',
    messagingSenderId: '525959382347',
    projectId: 'danush-52b93',
    authDomain: 'danush-52b93.firebaseapp.com',
    storageBucket: 'danush-52b93.firebasestorage.app',
    measurementId: 'G-8HKJGD6TFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDogExAaUCnLBtgc-kAbWAIlsTUoDEZ_3c',
    appId: '1:525959382347:android:300f49656e54a2231794ce',
    messagingSenderId: '525959382347',
    projectId: 'danush-52b93',
    storageBucket: 'danush-52b93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdPp2z1xP0IOv2M6juXNrHY_cSZ2DXNEE',
    appId: '1:525959382347:ios:a36f784f54f1ffe41794ce',
    messagingSenderId: '525959382347',
    projectId: 'danush-52b93',
    storageBucket: 'danush-52b93.firebasestorage.app',
    iosBundleId: 'com.example.sampleSambhavam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdPp2z1xP0IOv2M6juXNrHY_cSZ2DXNEE',
    appId: '1:525959382347:ios:a36f784f54f1ffe41794ce',
    messagingSenderId: '525959382347',
    projectId: 'danush-52b93',
    storageBucket: 'danush-52b93.firebasestorage.app',
    iosBundleId: 'com.example.sampleSambhavam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA7gI3qG4YuOzg4YlP8HuurMIl-qyvODs',
    appId: '1:525959382347:web:0f2b1af09ddf37d61794ce',
    messagingSenderId: '525959382347',
    projectId: 'danush-52b93',
    authDomain: 'danush-52b93.firebaseapp.com',
    storageBucket: 'danush-52b93.firebasestorage.app',
    measurementId: 'G-WCQPMV136E',
  );

}