// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvK8RnnbGDuCBERY99FRsQ1bW9Rt9BGo4',
    appId: '1:631137199847:web:be0e4c809dea99fe69e442',
    messagingSenderId: '631137199847',
    projectId: 'bustrackingapp-467c9',
    authDomain: 'bustrackingapp-467c9.firebaseapp.com',
    storageBucket: 'bustrackingapp-467c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2DDPKmw3h0DerjcPoarCyE1zGpbtWEpI',
    appId: '1:631137199847:android:80bfc7e5d7880a6a69e442',
    messagingSenderId: '631137199847',
    projectId: 'bustrackingapp-467c9',
    storageBucket: 'bustrackingapp-467c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqO1dTHeJwm2ffXfl59IDdURXNsM0UzTY',
    appId: '1:631137199847:ios:2e754e4cfcb4515669e442',
    messagingSenderId: '631137199847',
    projectId: 'bustrackingapp-467c9',
    storageBucket: 'bustrackingapp-467c9.firebasestorage.app',
    iosBundleId: 'com.example.sampleSambhavam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqO1dTHeJwm2ffXfl59IDdURXNsM0UzTY',
    appId: '1:631137199847:ios:2e754e4cfcb4515669e442',
    messagingSenderId: '631137199847',
    projectId: 'bustrackingapp-467c9',
    storageBucket: 'bustrackingapp-467c9.firebasestorage.app',
    iosBundleId: 'com.example.sampleSambhavam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvK8RnnbGDuCBERY99FRsQ1bW9Rt9BGo4',
    appId: '1:631137199847:web:59899f49871cb8c269e442',
    messagingSenderId: '631137199847',
    projectId: 'bustrackingapp-467c9',
    authDomain: 'bustrackingapp-467c9.firebaseapp.com',
    storageBucket: 'bustrackingapp-467c9.firebasestorage.app',
  );
}
